### ISSUE TITLE
This repository is not currently assigned to the ContentMine/Administrators team

### ISSUE THREAD

**Issue by ghost** [ContentMine/svg#3]
Please could someone listed [here](https://github.com/orgs/ContentMine/teams/administrators) as a "Maintainer" (e.g. @petermr , @markmacgillivray , or @tarrow ) add the [ContentMine/svg](https://github.com/ContentMine/svg) repository to [the team's repository list](https://github.com/orgs/ContentMine/teams/administrators/repositories) per [these instructions](https://github.com/orgs/ContentMine/teams/administrators/repositories)? Thank you in advance :)

**Comment by tarrow** [comment]
@sampablokuper Done!

Are there other repos with this problem?

**Comment by ghost** [comment]
@tarrow thanks!

There are indeed other repos with this problem. Have now filed a [meta issue](https://github.com/ContentMine/meta/issues/3).

Apologies for not being able to fix this myself (as am not listed as a "Maintainer").
